import { writeTextAtomic } from "../core/workspace.js";
import { isPrimaryArchitectureSymbol } from "../analysis/scope.js";
import type { Atlas } from "../ir/models.js";

function mermaidLabel(value: string): string {
  return value.replace(/["[\]{}<>]/gu, " ").replace(/\s+/gu, " ").trim().slice(0, 80);
}

export function renderAtlasMermaid(atlas: Atlas): string {
  const symbolById = new Map(atlas.symbols.map((symbol) => [symbol.id, symbol]));
  const domains = atlas.domains.filter((domain) =>
    domain.member_ids.some((id) => {
      const symbol = symbolById.get(id);
      return symbol !== undefined && isPrimaryArchitectureSymbol(symbol);
    }),
  );
  const domainBySymbol = new Map<string, string>();
  for (const domain of domains) {
    for (const id of domain.member_ids) {
      const symbol = symbolById.get(id);
      if (symbol && isPrimaryArchitectureSymbol(symbol)) domainBySymbol.set(id, domain.id);
    }
  }
  const nodes = domains.length > 0
    ? domains.map((domain) => ({ id: domain.id, label: domain.name, detail: `${domain.file_ids.length} files` }))
    : atlas.symbols
      .filter((symbol) => symbol.kind === "file" && isPrimaryArchitectureSymbol(symbol))
      .slice(0, 100)
      .map((symbol) => ({ id: symbol.id, label: symbol.file ?? symbol.name, detail: "file" }));
  const aliases = new Map(nodes.map((node, index) => [node.id, `n${index}`]));
  const edgeCounts = new Map<string, { source: string; target: string; count: number; potential: boolean }>();
  for (const relationship of atlas.relationships) {
    const sourceSymbol = symbolById.get(relationship.source);
    const targetSymbol = symbolById.get(relationship.target);
    if (!sourceSymbol || !targetSymbol) continue;
    const source = domains.length > 0 ? domainBySymbol.get(sourceSymbol.id) : sourceSymbol.kind === "file" ? sourceSymbol.id : undefined;
    const target = domains.length > 0 ? domainBySymbol.get(targetSymbol.id) : targetSymbol.kind === "file" ? targetSymbol.id : undefined;
    if (!source || !target || source === target || !aliases.has(source) || !aliases.has(target)) continue;
    const key = `${source}\0${target}`;
    const prior = edgeCounts.get(key);
    edgeCounts.set(key, {
      source,
      target,
      count: (prior?.count ?? 0) + 1,
      potential: (prior?.potential ?? false) || relationship.confidence < 0.95,
    });
  }
  const lines = [
    "%% Generated by CodeAtlas. Solid edges are definite; dashed edges include potential relationships.",
    "flowchart LR",
    ...nodes.map((node) => `  ${aliases.get(node.id)}["${mermaidLabel(node.label)}<br/><small>${mermaidLabel(node.detail)}</small>"]`),
    ...[...edgeCounts.values()]
      .sort((left, right) => left.source.localeCompare(right.source) || left.target.localeCompare(right.target))
      .map((edge) => `  ${aliases.get(edge.source)} ${edge.potential ? "-." : "--"} "${edge.count}" ${edge.potential ? ".->" : "-->"} ${aliases.get(edge.target)}`),
    "",
  ];
  return lines.join("\n");
}

export async function exportAtlasMermaid(atlas: Atlas, outputPath: string): Promise<void> {
  await writeTextAtomic(outputPath, renderAtlasMermaid(atlas));
}
